version: '3.8'

services:
  buildkitd:
    image: moby/buildkit:master-rootless
    container_name: buildkitd
    command:
      - --addr
      - unix:///run/user/1000/buildkit/buildkitd.sock
      - --addr
      - tcp://0.0.0.0:5000
      - --tlscacert
      - /certs/ca.pem
      - --tlscert
      - /certs/cert.pem
      - --tlskey
      - /certs/key.pem
      - --oci-worker-no-process-sandbox
    ports:
      - "5000:5000"
    volumes:
      - ./buildkitd_certs:/certs:ro
      - buildkitd_data:/home/user/.local/share/buildkit
    user: "1000:1000"
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD", "buildctl", "debug", "workers"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s
    deploy:
      resources:
        limits:
          cpus: "10"
          memory: "20G"

volumes:
  buildkitd_data:
