apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildkit-pvc
spec:
  storageClassName: topolvm-provisioner
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
